### PR TITLE
bump to 1.0.2

### PR DESCRIPTION
**Pull request by h-vetinari**
There's been a couple of new releases since, seems the bot is not picking up the `tar.xz` files from github? Any reason not to use the `tar.gz` source releases?

### CODE REVIEW

**Comment by h-vetinari** [comment]
@conda-forge/runc 
This is green and ready

**Comment by h-vetinari** [comment]
Ping @mbargull

**Comment by h-vetinari** [comment]
Ping @conda-forge/core
This has received no response in ~3 months. If desired, I can add myself to maintainers (here or with the next version update; 1.0.2 has been released already).

**Comment by jaimergp** [comment]
Add yourself and I'll merge!

**Comment by h-vetinari** [comment]
> Add yourself and I'll merge!

Done! And congrats on joining core! :)

**Comment by jaimergp** [comment]
Wow Chris stole my merge 😂

**Comment by h-vetinari** [comment]
> 
> 
> Wow Chris stole my merge 😂

Don't worry, you'll get plenty 😋

**Pull request merged**
